-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN 
    (
        SELECT TREE.ITEM_ID
        FROM ITEM_TREE AS TREE JOIN ITEM_INFO AS INFO ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
        WHERE RARITY = 'RARE'
    )
ORDER BY ITEM_ID DESC