-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (SIZE - SIZE_OF_COLONY)AS YEAR_DEV, ID
FROM ECOLI_DATA AS A JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON B.Y = YEAR(A.DIFFERENTIATION_DATE) 
ORDER BY YEAR, YEAR_DEV

