-- 코드를 작성해주세요
SELECT ID, FISH_NAME, L AS LENGTH
FROM FISH_INFO AS F JOIN
(SELECT FISH_TYPE, MAX(IFNULL(LENGTH, 0)) AS L
FROM FISH_INFO 
GROUP BY FISH_TYPE) AS A
ON F.LENGTH = A.L AND F.FISH_TYPE = A.FISH_TYPE 
JOIN FISH_NAME_INFO AS C 
ON A.FISH_TYPE = C.FISH_TYPE

