-- 코드를 작성해주세요
SELECT DE.DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS DE JOIN HR_EMPLOYEES AS EM ON DE.DEPT_ID = EM.DEPT_ID
GROUP BY DE.DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC
