-- 코드를 입력하세요
SELECT A.CATEGORY, SUB_MAX_PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS A
    JOIN 
        (SELECT CATEGORY, MAX(PRICE) AS SUB_MAX_PRICE
        FROM FOOD_PRODUCT 
        WHERE CATEGORY IN('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY) AS B
    ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.SUB_MAX_PRICE
ORDER BY MAX_PRICE DESC
